import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryWrapper from "./react-query-wrapper";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/theme-provider";
import ThemeStateProvider from "./theme-state-provider";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body className={inter.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <ThemeStateProvider>
                        <ReactQueryWrapper>{children}</ReactQueryWrapper>
                    </ThemeStateProvider>
                </ThemeProvider>
                <Toaster />
            </body>
        </html>
    );
}
